export const GET_DISTRICTS_FARMS = "GET_DISTRICTS_FARMS";
export const SET_ACTIVE_FARM = "SET_ACTIVE_FARM";
export const GET_ACTIVE_TECHNICS = "GET_ACTIVE_TECHNICS";
export const GET_TECH_GROUP = "GET_TECH_GROUP";
export const GET_TECH_STATUS = "GET_TECH_STATUS";
export const SET_EDIT_TECHICS = "SET_EDIT_TECHICS";
export const GET_ACTIVE_DISTRICT_ID = "GET_ACTIVE_DISTRICT_ID";